<?php
/**
 * Created by PhpStorm.
 * User: 升值中
 * Date: 2017-07-25
 * Time: 19:02
 */
namespace backend\models;
use yii\base\Model;

class Loginx extends Model{
    public $password_l;
    public $password_x;
    public $password_z;
    public function rules()
    {
        //return parent::rules(); // TODO: Change the autogenerated stub
        return[
          [['password_l','password_x','password_z'],'required'],
            ['password_z', 'compare', 'compareAttribute' => 'password_x','message' => '两次密码输入不一致']
        ];
    }
    public function attributeLabels(){
        return[
            'password_l'=>'旧密码',
            'password_x'=>'新密码',
            'password_z'=>'再次输入新密码',
        ];
    }

}