<?php
/**
 * Created by PhpStorm.
 * User: 升值中
 * Date: 2017-07-26
 * Time: 14:26
 */
namespace backend\models;
use yii\base\Model;

class PermissionForm extends Model{
    const SCENARIO_ADD='add';


    public $name;
    public $description;
    public function rules()
    {
        return [
          [['name','description'],'required'],
            //权限名不能重复
          ['name','validateName','on'=>self::SCENARIO_ADD],
        ];
    }
    public function attributeLabels()
    {
        return[
            'name'=>'名称(路由)',
            'description'=>'描述',
        ];
        //return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    //自定义验证规则
    //只判断成立的情况
    public function validateName(){
        $authManger=\yii::$app->authManager;
        if($authManger->getPermission($this->name)){
            $this->addError('name','权限已存在');
        }
    }
}