<?php
/**
 * Created by PhpStorm.
 * User: 升值中
 * Date: 2017-07-27
 * Time: 23:48
 */
namespace backend\models;
use yii\base\Model;

class RoleForm extends Model{
    const SCENARIO_ADD='add';
    public $name;
    public $description;
    public $permissions=[];

    public function rules()
    {
        return [
            [['name','description'],'required'],
            ['permissions','safe'],
            ['name','validateName','on'=>self::SCENARIO_ADD],
            //角色名不能重复
            //['name']
        ];
    }
    public function attributeLabels()
    {
        return[
            'name'=>'角色名称',
            'description'=>'角色描述',
            'permissions'=>'角色权限',

        ];
        //return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
    public function validateName(){
        $authManger=\yii::$app->authManager;
        if($authManger->getPermission($this->name)){
            $this->addError('name','权限已存在');
        }
    }
}