<?php
/**
 * Created by PhpStorm.
 * User: 升值中
 * Date: 2017-07-30
 * Time: 15:32
 */
namespace frontend\models;
use yii\db\ActiveRecord;

class Address extends ActiveRecord{
    public function rules()
    {
        return [
            [['name','sid','cid','xid','site','tal'],'required'],
            ['status','safe'],
            ];//parent::rules(); // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '收货人：',
            'sid' => '省',
            'cid'=>'市',
            'xid'=>'县',
            'site' => '详细地址：',
            'tal' => '手机号码：',
            'status' => '设为默认地址',
        ];
    }

    public static function getName($id){
        $name=City::find()->select('name')->where(['id'=>$id])->one();
        return $name;
    }
}