<?php
/**
 * Created by PhpStorm.
 * User: 升值中
 * Date: 2017-07-30
 * Time: 10:20
 */
namespace frontend\models;
use yii\base\Model;

class LoginFrom extends Model{
    public $username;
    public $password;
    public $rememberMe;
    public function rules()
    {
        return [
            [['username','password'],'required'],
            ['rememberMe','boolean'],
        ];//parent::rules(); // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return [
            'username'=>'用户名：',
            'password'=>'密码：',
            'rememberMe'=>'是否自动登录',
        ];//parent::attributeLabels(); //TODO: Change the autogenerated stub
    }
    public function Login(){
        //根据用户提交的信息去数据库查找
        $member=Member::findOne(['username'=>$this->username]);
        //判断是否查找到数据
        if($member){
            //判断密码是否正确
            if(\yii::$app->security->validatePassword($this->password,$member->password_hash)){
                //判断用户是否勾选自动登录
                \yii::$app->user->login($member,$this->rememberMe?3*24*3600:0);
                return true;
            }else{
                $this->addError('password', '密码不正确');
            }
        }else{
            //用户不存在输出
            $this->addError('username', '用户名不存在');
        }
        return false;
    }
}